name: arab-ocr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - flask
  - pillow
  - requests
  - pip:
    - transformers
    - openai
    - arabic-reshaper
    - python-bidi
    - accelerate
    - safetensors
    - sentencepiece
